apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: prt2sjok1-python 
  janus-idp.io/tekton: prt2sjok1-python
  backstage.io/kubernetes-id: prt2sjok1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: prt2sjok1-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml